name: Aprendiendo GitHub Actions

on:
  push:

jobs:
  hola_mundo:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13 ' 
        - name: Run Script
          run: python main.py

        
        